---

- include: clear_result.yml

- block:
    - name: "Host's ssh port is open from perspective of {{ accessible_wait_for_delegate }}"
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port | default(accessible_ssh_port) }}"
        # Fail quickly == retry sooner
        connect_timeout: 1
        # Minumum is two-DNS failures + one second
        timeout: "{{ accessible_retries | int * accessible_delay | int }}"
        state: "started"
      delegate_to: '{{ accessible_wait_for_delegate }}'
      register: result
      until: result | success
      retries: '{{ accessible_retries }}'
      delay: '{{ accessible_delay }}'
      when: ansible_connection in accessible_ssh_types

    - name: "Ansible accessability command executes successfully"
      raw: '{{ accessible_cmd }}'  # raw has no subject-host dependencies
      changed_when: False  # inspection only
      register: result
      until: result | success
      retries: '{{ accessible_retries }}'
      delay: '{{ accessible_delay }}'

  rescue:
    - name: "Failure result of accessible_cmd is debugged"
      debug:
        var: result.results[-1]  # Last one must have failed
