---

- name: 'Accessible tasks expectations are met'
  assert:
    that:
        - 'accessible_cmd is string'
        - 'accessible_retries | int > 0'
        - 'accessible_delay | int > 12'
        - 'accessible_wait_for_delegate == "localhost" or
           accessible_wait_for_delegate in hostvars | list'
        - 'accessible_ansible_deps is mapping'
        - 'accessible_gather_subset is string'
        - 'ansible_connection | trim in accessible_ssh_types'

- include_tasks: clear_result.yml

- name: Script command is formed for checking multiple ports
  set_fact:
    result: 'wait_for.sh {{ accessible_retries | int }} {{ accessible_delay | int }} {{ ansible_host }} {{ accessible_ssh_port | join (" ") }}'
  when: not accessible_ssh_port is string and
        not accessible_ssh_port is mapping and
            accessible_ssh_port is sequence

- name: Script command is formed to checking on a single port
  set_fact:
    result: 'wait_for.sh {{ accessible_retries | int }} {{ accessible_delay | int }} {{ ansible_host }} {{ accessible_ssh_port | int }}'
  when: not result | default("", True) | trim | length

- name: 'Wait for a port to open or timeout using a script'
  script: '{{ result }}'
  delegate_to: "{{ accessible_wait_for_delegate }}"
  changed_when: False
  register: result

- name: 'The first found open port is set as ansible_port for this host'
  set_fact:
    ansible_port: '{{ result.stdout | trim | int }}'
  when: accessible_set_ansible_port | bool
