---

- include: clear_result.yml

- name: "Ansible accessability command executes successfully"
  raw: '{{ accessible_cmd }}'  # raw has no subject-host dependencies
  changed_when: False  # inspection only
  register: result
  until: result is success
  retries: '{{ accessible_retries }}'
  delay: '{{ accessible_delay }}'
