---

- include: clear_result.yml

- name: Host facts gather successfully when depds are already met.
  setup:
    gather_subset: min
  failed_when: False
  ignore_errors: True
  register: result

- when: result is failed
  block:

    - include: clear_result.yml

    - name: "Command is buffered from accessible_ansible_deps lookup table"
      set_fact:
        result: '{{ accessible_ansible_deps[accessible_os_name][accessible_os_version] }}'
      when: accessible_os_name in accessible_ansible_deps and
            accessible_os_version in accessible_ansible_deps[accessible_os_name]

    - name: "Either the buffered command or the default is executed"
      raw: '{{ result | default(accessible_ansible_deps["default"], True) }}'
      when: accessible_ansible_deps["default"] | trim | length

    - name: Host facts are gathered after dependencies satisfied
      setup:
        gather_subset: '{{ accessible_gather_subset }}'
