---

- name: Attempt to retrieve facts, ignoring any errors
  setup:
    gather_subset: min
  ignore_errors: True
  when: ansible_local is undefined

- when: ansible_local is undefined or
        not ansible_local.accessible_deps_cmd_was_run | default(False, True) | bool
  block:

    - include: clear_result.yml

    - name: "Command is buffered from accessible_ansible_deps lookup table"
      set_fact:
        result: '{{ accessible_ansible_deps[accessible_os_name][accessible_os_version] }}'
      when: accessible_os_name in accessible_ansible_deps and
            accessible_os_version in accessible_ansible_deps[accessible_os_name]

    - name: The lookup result is debugged
      debug: var=result

    - name: "Either the buffered command or the default is executed"
      raw: '{{ result | default(accessible_ansible_deps["default"], True) }}'
      when: accessible_ansible_deps["default"] | trim | length
      register: result

    - name: The Ansible local-facts directory exists to record role-state.
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: The role-state is recorded
      copy:
        dest: /etc/ansible/facts.d/accessible_deps_cmd_was_run.fact
        content: "true"
