---

- include_tasks: accessible.yml
  when: ansible_connection | default('ssh') in accessible_ssh_types

- include_tasks: clear_result.yml

- include_tasks: test_command.yml

- include_tasks: os_detection.yml

- name: 'RHEL hosts apply the cevich.subscribed role before installing dependencies'
  import_role:
    name: cevich.subscribed
    private: True
  when: accessible_os_name == 'rhel' and
        rhsm | default({}, True) | length and
        rhsm.username | default("", True) | trim | length and
        rhsm.password | default("", True) | trim | length

- include: dependencies.yml

- name: 'Host facts are re-gathered after dependencies satisfied'
  setup:
    gather_subset: '{{ accessible_gather_subset }}'
