---

- include: accessable.yml

- include: os_detection.yml

- name: RHEL hosts apply the cevich.subscribed role before installing dependencies
  import_role:
    name: cevich.subscribed
    private: True
  when: accessable_os_name == 'rhel' and
        rhsm | default({}, True) | length and
        rhsm.username | default("", True) | trim | length and
        rhsm.password | default("", True) | trim | length

- include: dependencies.yml
